export * from './types/index.js';
export { cacheManager } from './api/memoryCacheManager.js';
export { RateLimiter, beforeRequest, getAntiScrapeHeaders } from './api/antiScrape.js';
export type { AntiScrapeHeaders } from './api/antiScrape.js';
export { musicApi, setApiBaseUrl, getApiBaseUrl, getApiClient, setProxyUrl, getProxyUrl, warmUpArtistPicCache, injectProxyAgents } from './api/musicApi.js';
export type { ProxyAgents } from './api/musicApi.js';
export { dedupeSongs, checkDuplicate, filterDuplicates } from './utils/songDedupe.js';
export type { DupStatus, DupResult, FilterResult } from './utils/songDedupe.js';
export { calculateSimilarity, findBestMatch } from './utils/songMatcher.js';
export { createResolveSongUrls } from './utils/songResolver.js';
export type { SearchFn } from './utils/songResolver.js';
export { createAxiosTransport } from './api/axiosTransport.js';
export type { Transport, TransportConfig, TransportResponse } from './api/transport.js';
export { parseLRC, findCurrentLyricIndex, formatLyricsTime, generateLRC } from './utils/lyricsParser.js';
export type { LyricLine, ParsedLyrics } from './utils/lyricsParser.js';
export { formatPlayCount } from './utils/format.js';
export { createSearchController } from './shared/searchController.js';
export type { SearchController, SearchControllerConfig } from './shared/searchController.js';
export { resolvePlayableUrl } from './shared/resolvePlayableUrl.js';
export type { UrlResolver } from './shared/resolvePlayableUrl.js';
export { CacheKernel } from './cache/cacheKernel.js';
export { createMemoryBackend } from './cache/backends/memoryBackend.js';
export { DEFAULT_TTL } from './cache/ttl.js';
export type { CachePort, CacheBackend, CacheStats } from './cache/types.js';
